# config.py

# =============================================================================
# Run switches
# =============================================================================

# Options: "train", "test"
CONFIG_MODE = "test"

# Options: True, False
# True: run build_pretrain_original_from_docs -> data_prep -> tokenizer
#       -> tokenizer_eval -> pretrain -> sft.
# False: start from TRAIN_STAGE and continue through the remaining pipeline stages.
RUN_FULL_PIPELINE = True

# Options when RUN_FULL_PIPELINE is False:
# "build_pretrain_original_from_docs", "data_prep", "tokenizer",
# "tokenizer_eval", "pretrain", "sft"
# Ignored when RUN_FULL_PIPELINE is True.
TRAIN_STAGE = "sft"


# =============================================================================
# Output root
# =============================================================================

# All generated training artifacts are written under this directory.
# Original source data and document inputs remain under data/.
OUTPUT_ROOT = "outputs"


# =============================================================================
# Data paths
# =============================================================================

# Document-to-JSONL build paths.
DOCS_INPUT_DIR = "data/docs"
DOCS_PRETRAIN_OUTPUT_PATH = (
    f"{OUTPUT_ROOT}/data/original/pretrain_original_from_docs.jsonl"
)



# Original source data.
# Final unified pretraining source used by downstream data_prep/pretrain stages.
PRETRAIN_ORIGIN_DATA = f"{OUTPUT_ROOT}/data/original/pretrain_original.jsonl"

# Original Happy-LLM pretraining data. This file should be preserved and
# should not be overwritten by document-building or merge logic.
PRETRAIN_HAPPY_ORIGIN_DATA = "data/original/pretrain_original_happy.jsonl"

SFT_ORIGIN_DATA = "data/original/sft_original.json"


# =============================================================================
# Pretrain original data source when skipping document-building stage
# =============================================================================
# Options:
# "merged": use the existing merged pretrain_original.jsonl.
#           This is the default option. It assumes that pretrain_original.jsonl
#           has already been generated by a previous full pipeline run or by
#           manually running build_pretrain_original_from_docs.
#
# "happy":  use only the original Happy-LLM pretraining data.
#           In this mode, pretrain_original_happy.jsonl will be copied or
#           safely regenerated as pretrain_original.jsonl.
#
# This switch is only used when the pipeline does NOT start from
# build_pretrain_original_from_docs.
PRETRAIN_ORIGINAL_SOURCE_WHEN_SKIP_DOCS = "merged"


# =============================================================================
# Pretrain original data amount control
# =============================================================================
# CONFIG_MODE = "train": use all available records from every source.
# CONFIG_MODE = "test": write a small pretrain_original.jsonl for fast pipeline
# verification after document-building and merge.
PRETRAIN_TEST_HAPPY_LIMIT = 50
PRETRAIN_TEST_DOCS_LIMIT = 50


# =============================================================================
# SFT data amount control
# =============================================================================
# CONFIG_MODE = "train": use all available SFT records.
# CONFIG_MODE = "test": use only the first valid records for fast verification.
SFT_TEST_LIMIT = 100


# =============================================================================
# Validation config
# =============================================================================
# Ratio of processed data used for validation during model training.
VAL_RATIO = 0.05

# Run validation every N training steps. Set to 0 to disable step validation.
VAL_INTERVAL = 100


# Processed training data.
PRETRAIN_TRAIN_DATA = f"{OUTPUT_ROOT}/data/train/pretrain_train.jsonl"
SFT_TRAIN_DATA = f"{OUTPUT_ROOT}/data/train/sft_train.json"


# =============================================================================
# Tokenizer paths
# =============================================================================

TOKENIZER_TRAIN_DATA_PATH = PRETRAIN_TRAIN_DATA
TOKENIZER_SAVE_DIR = f"{OUTPUT_ROOT}/tokenizer_k"
TOKENIZER_NAME = TOKENIZER_SAVE_DIR


# =============================================================================
# Output paths
# =============================================================================

LOG_DIR = f"{OUTPUT_ROOT}/runs"
TEXT_LOG_DIR = f"{OUTPUT_ROOT}/logs"
PRETRAIN_CHECKPOINT_DIR = f"{OUTPUT_ROOT}/checkpoints/pretrain"
SFT_CHECKPOINT_DIR = f"{OUTPUT_ROOT}/checkpoints/sft"
EXPORT_SAVE_ROOT = f"{OUTPUT_ROOT}/save_model"


# =============================================================================
# Resume settings
# =============================================================================

# Options: True, False
# True: resume training. If RESUME_CHECKPOINT_PATH is empty, train.py finds
# the latest checkpoint in the active stage checkpoint directory.
RESUME = False
RESUME_CHECKPOINT_PATH = ""

# Empty: train.py automatically finds the latest pretrain checkpoint for SFT init.
# Non-empty: use the specified checkpoint path for SFT initialization.
SFT_INIT_CHECKPOINT_PATH = ""


# =============================================================================
# Tokenizer config
# =============================================================================

VOCAB_SIZE = 10000


# =============================================================================
# Prompt
# =============================================================================

SYSTEM_PROMPT = "你是一个AI助手"


# =============================================================================
# Model architecture configs
# =============================================================================

MODEL_TRAIN_CONFIG = {
    "DIM_EMBEDDING": 1024,
    "N_HEADS": 16,
    "N_LAYERS": 18,
    "N_KV_HEADS": 8,
    "NORM_EPS": 1e-5,
    "DROPOUT": 0.0,
    "MULTIPLE_OF": 64,
}

MODEL_TEST_CONFIG = {
    "DIM_EMBEDDING": 128,
    "N_HEADS": 4,
    "N_LAYERS": 2,
    "N_KV_HEADS": 2,
    "NORM_EPS": 1e-5,
    "DROPOUT": 0.0,
    "MULTIPLE_OF": 64,
}


# =============================================================================
# Runtime and training configs
# =============================================================================

TRAIN_CONFIG = {
    "SEED": 42,
    "NUM_WORKERS": 0,
    "USE_AMP": True,  # Options: True, False
    "BATCH_SIZE": 12,
    "MAX_SEQ_LEN": 512,
    "EPOCHS": 2,
    "LEARNING_RATE": 1e-4,
    "ACCUMULATION_STEPS": 8,
    "WARMUP_ITERS": 0,
    "GRAD_CLIP": 1.0,
    **MODEL_TRAIN_CONFIG,
    "LOG_INTERVAL": 100,
    "SAVE_EVERY_STEPS": 20000,
    "SAVE_EVERY_EPOCHS": 1,
    "MAX_NEW_TOKENS": 512,
    "TEMPERATURE": 1.0,
    "TOP_K": 1,
    "STREAM": True,  # Options: True, False
}

TEST_CONFIG = {
    "SEED": 42,
    "NUM_WORKERS": 0,
    "USE_AMP": False,  # Options: True, False
    "BATCH_SIZE": 1,
    "MAX_SEQ_LEN": 64,
    "EPOCHS": 1,
    "LEARNING_RATE": 1e-4,
    "ACCUMULATION_STEPS": 1,
    "WARMUP_ITERS": 0,
    "GRAD_CLIP": 1.0,
    **MODEL_TEST_CONFIG,
    "LOG_INTERVAL": 5,
    "SAVE_EVERY_STEPS": 20,
    "SAVE_EVERY_EPOCHS": 1,
    "MAX_NEW_TOKENS": 64,
    "TEMPERATURE": 0.9,
    "TOP_K": 1,
    "STREAM": True,  # Options: True, False
}


# =============================================================================
# Text generation sample config
# =============================================================================

# Options: "pretrain", "sft"
SAMPLE_STAGE = TRAIN_STAGE

# Empty checkpoint path: automatically use the latest checkpoint for SAMPLE_STAGE.
SAMPLE_CHECKPOINT_PATH = ""
SAMPLE_TOKENIZER_PATH = TOKENIZER_NAME
SAMPLE_SEED = 42
SAMPLE_DEVICE = ""  # Empty: automatically select CUDA or CPU.
SAMPLE_DTYPE = "float32"  # Options: "float32", "float16", "bfloat16"

SAMPLE_CONFIG_TABLE = {
    "pretrain": {
        "NUM_SAMPLES": 1,
        "MAX_NEW_TOKENS": 120,
        "TEMPERATURE": 0.75,
        "TOP_K": 3,
    },
    "sft": {
        "NUM_SAMPLES": 1,
        "MAX_NEW_TOKENS": 128,
        "TEMPERATURE": 0.6,
        "TOP_K": 3,
    },
}


# =============================================================================
# Stage configs
# =============================================================================

PIPELINE_STAGES = [
    "build_pretrain_original_from_docs",
    "data_prep",
    "tokenizer",
    "tokenizer_eval",
    "pretrain",
    "sft",
]

STAGE_CONFIG_TABLE = {
    "pretrain": {
        "DATA_PATH": PRETRAIN_TRAIN_DATA,
        "CHECKPOINT_DIR": PRETRAIN_CHECKPOINT_DIR,
        "CHECKPOINT_PREFIX": "transformer_pretrain",
        "CHECKPOINT_PATH": "transformer_pretrain_final.pt",
        "SFT_INIT_CHECKPOINT_PATH": "",
    },
    "sft": {
        "DATA_PATH": SFT_TRAIN_DATA,
        "CHECKPOINT_DIR": SFT_CHECKPOINT_DIR,
        "CHECKPOINT_PREFIX": "transformer_sft",
        "CHECKPOINT_PATH": "transformer_sft_final.pt",
        "SFT_INIT_CHECKPOINT_PATH": SFT_INIT_CHECKPOINT_PATH,
    },
}


# =============================================================================
# Config builder
# =============================================================================

def get_active_config(stage=None, mode=None):
    """Build a train/test config for model stages: "pretrain" or "sft"."""
    stage = stage or TRAIN_STAGE
    mode = mode or CONFIG_MODE

    mode_config_table = {
        "train": TRAIN_CONFIG,
        "test": TEST_CONFIG,
    }

    if mode not in mode_config_table:
        raise ValueError('CONFIG_MODE must be "train" or "test"')
    if stage not in STAGE_CONFIG_TABLE:
        raise ValueError(
            'get_active_config only supports model stages: "pretrain" or "sft"'
        )

    active = {}
    active.update(mode_config_table[mode])
    active.update(STAGE_CONFIG_TABLE[stage])

    return active


def get_sample_config(stage=None):
    """Return text-generation sample settings for pretrain or SFT."""
    stage = stage or SAMPLE_STAGE
    if stage not in SAMPLE_CONFIG_TABLE:
        raise ValueError('SAMPLE_STAGE must be "pretrain" or "sft"')
    return dict(SAMPLE_CONFIG_TABLE[stage])


def get_pretrain_original_source_limits(mode=None):
    """Return per-source limits for merged pretraining data."""
    mode = mode or CONFIG_MODE

    if mode == "train":
        return {
            "happy": None,
            "docs": None,
        }
    if mode == "test":
        return {
            "happy": PRETRAIN_TEST_HAPPY_LIMIT,
            "docs": PRETRAIN_TEST_DOCS_LIMIT,
        }

    raise ValueError('CONFIG_MODE must be "train" or "test"')


def get_sft_data_limit(mode=None):
    """Return the SFT record limit for the active config mode."""
    mode = mode or CONFIG_MODE

    if mode == "train":
        return None
    if mode == "test":
        return SFT_TEST_LIMIT

    raise ValueError('CONFIG_MODE must be "train" or "test"')
